name: Decode and Save Keystore

on:
  workflow_dispatch:

jobs:
  decode:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Decode keystore file
        env:
          BASE64_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
        run: |
          echo "$BASE64_KEYSTORE" | base64 -d > user.keystore
          ls -l user.keystore

      - name: Upload keystore as artifact
        uses: actions/upload-artifact@v4
        with:
          name: user-keystore
          path: user.keystore
